name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['gpc_cache_ci']
  pull_request:
  workflow_dispatch:

env:
  verilator-version: v5.022
  verilator-install-dir: verilator-install

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        run: sed -i "s/grapecoveDCache[chisel3]/test/g" build.sc
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt mill
      - name: Setup Dependencies
        run: |
          sudo apt-get install ccache
      - name: Get Cached Verilator
        id: get-cached-verilator
        uses: actions/cache@v4
        with:
          path: ${{ env.verilator-install-dir }}
          key: verilator-${{ env.verilator-version }}
      - name: Install Verilator
        if: steps.get-cached-verilator.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install git help2man perl python3 make autoconf g++ flex bison numactl perl-doc libfl-dev
      - name: test
        run: |
          make init
          mill resolve _
          mill resolve __.test
          mill _.test