name: GPC DCache Test

on:
  push:
    tags: ['*']
    branches: ['gpc_cache*']
  pull_request:
  workflow_dispatch:

# find verilator binaries here https://repology.org/project/verilator/versions
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cleanup
        run: sed -i "s/grapecoveDCache[chisel3]/test/g" build.sc
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt mill
      - name: Setup Dependencies
        run: |
          sudo apt-get install ccache
      - name: Install Verilator
        run: |
          sudo apt-get install verilator
      - name: test
        run: |
          make init  
          make test


# sudo apt-get install git help2man perl python3 make autoconf g++ flex bison numactl perl-doc libfl-dev
# wget https://github.com/verilator/verilator/archive/v4.218/verilator-4.218.tar.gz 
# tar -xf verilator-4.218.tar.gz
# mv verilator-4.218 verilator
# unset VERILATOR_ROOT
# - name: Set PATH
# run: |
# echo "$(pwd)/verilator/bin" >> $GITHUB_PATH
# echo VERILATOR_ROOT="$(pwd)/verilator" >> $GITHUB_ENV
# ln -sf $(pwd)/verilator/verilator_bin $(pwd)/verilator/bin
